---
version: "2.1"
services:
  etherpad:
    image: nicholaswilde/etherpad
    container_name: etherpad
    ports:
      - 9001:9001
    restart: unless-stopped
    volumes:
      - data:/opt/etherpad-lite/var
      - app:/opt/etherpad-lite
volumes:
  data:
  app:
