---
name: hadolint
'on':
  pull_request:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
 
      - name: Hadolint Action
        # You may pin to the exact commit or the version.
        uses: brpaz/hadolint-action@v1.3.1
        with:
          # The path to the Dockerfile to lint
          dockerfile: Dockerfile # optional, default is Dockerfile
